name: shake_and_sip_app
description: third intern project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.3.2
  
  flutter_bloc: ^8.0.3
  flutter_screenutil: ^5.8.4
  hive_flutter:
  equatable:
  go_router: ^10.0.0
  flutter_animate: ^4.2.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
