// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfGQ92_M0NG_WOosQh9eoh2ZieV_fX_Xg',
    appId: '1:827582370341:web:65997ed64a06749fdba5cc',
    messagingSenderId: '827582370341',
    projectId: 'shakeandsipp',
    authDomain: 'shakeandsipp.firebaseapp.com',
    storageBucket: 'shakeandsipp.appspot.com',
    measurementId: 'G-VSE3XJ4HXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBnaeuKrrzxk4oIUsZqQpaiCxctWUvOKs',
    appId: '1:827582370341:android:7e69b3f47444a250dba5cc',
    messagingSenderId: '827582370341',
    projectId: 'shakeandsipp',
    storageBucket: 'shakeandsipp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMXAa8xFpPopLDkbtgQI6deCSw605PLPg',
    appId: '1:827582370341:ios:49e6556d5dfc62aedba5cc',
    messagingSenderId: '827582370341',
    projectId: 'shakeandsipp',
    storageBucket: 'shakeandsipp.appspot.com',
    iosClientId: '827582370341-sreffec10thq6oq6vpuufhhnut8hfjfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.shakeAndSip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMXAa8xFpPopLDkbtgQI6deCSw605PLPg',
    appId: '1:827582370341:ios:2e52a8d7367a9b2bdba5cc',
    messagingSenderId: '827582370341',
    projectId: 'shakeandsipp',
    storageBucket: 'shakeandsipp.appspot.com',
    iosClientId: '827582370341-08vv3f53048rfp1t6bhunaeokcl1kca5.apps.googleusercontent.com',
    iosBundleId: 'com.example.shakeAndSip.RunnerTests',
  );
}
